# Site settings
title: Zoji Docs
email: info@zoji.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.zoji.co" # the base hostname & protocol for your site
twitter_username: zoji
github_username:  zoji
categories: ux models

# Build settings
markdown: kramdown
